name: Build App
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Create Release'
        default: 'No'
        required: false
        type: choice
        options:
          - 'Yes'
          - 'No'

  push:
    branches:
      - main

jobs:
  prepare:
    name: Prepare
    if: startsWith(github.event.head_commit.message, 'Release') || startsWith(github.event.head_commit.message, 'Build')
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      version: ${{ steps.package-version.outputs.current-version }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: YeonV/yeonic
          ref: main
          fetch-depth: 0

      - name: Get commit-messages
        if: startsWith(github.event.head_commit.message, 'Release') || github.event.inputs.release == 'Yes'
        continue-on-error: true
        id: get_messages
        run: |
          git log --pretty=format:"+ %s [\![by](https://img.shields.io/badge/by-$(echo '%an' | sed 's/ /_/g')-blue.svg?logo=github&logoColor=white)](https://github.com/YeonV/yeonic/commit/%h)" $(git describe --tags --abbrev=0 @^)..@ | grep -v -E '(cleanup|Update)' | awk '{ sub(/\[\[!\]\]/, ""); msg = substr($0, 1, index($0, "[!") - 1); if (length(msg) >= 5 && !seen[msg]++) { print $0 } }' | awk '{ while (match($0, /https:\/\/img\.shields\.io\/badge\/by-[^"]*-blue\.svg\?logo=github&logoColor=white/)) { url = substr($0, RSTART, RLENGTH); gsub(" ", "_", url); printf "%s%s", substr($0, 1, RSTART - 1), url; $0 = substr($0, RSTART + RLENGTH) } gsub(" ", "_", $0); print }' >> /tmp/messages.txt
          cp /tmp/messages.txt .messages.md
          cat /tmp/messages.txt
          echo 'MESSAGES<<EOF' >> $GITHUB_ENV
          printf '%b\n' "$(cat /tmp/messages.txt)" >> $GITHUB_ENV
          echo EOF >> $GITHUB_ENV

      - name: get-npm-version
        id: package-version
        # uses: martinbeentjes/npm-get-version-action@1.3.1
        run: |
          PACKAGE_JSON_PATH="${1-.}"
          echo "Reading package.json from ${PACKAGE_JSON_PATH}/package.json"
          PACKAGE_VERSION=$(cat ${PACKAGE_JSON_PATH}/package.json | jq '.version' | tr -d '"')

          echo "current-version=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
      - name: Create Release
        if: startsWith(github.event.head_commit.message, 'Release') || github.event.inputs.release == 'Yes'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: Release ${{ steps.package-version.outputs.current-version }}
          body: |
            ${{ env.MESSAGES || 'New Relase' }}
          draft: false
          prerelease: false

  Build_Mobile:
    needs: prepare
    if: startsWith(github.event.head_commit.message, 'Release') || startsWith(github.event.head_commit.message, 'Build')
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
        include:
          - os: ubuntu-latest
            target: Android-APK
          - os: macos-14
            target: iOS-IPA
    runs-on: ${{ matrix.os }}
    name: Build Mobile (${{ matrix.target }})
    steps:
      - name: Checkout source
        if: startsWith(matrix.target, 'Android-APK')
        uses: actions/checkout@v4
        with:
          repository: YeonV/yeonic
          ref: main

      - name: Setup java
        if: startsWith(matrix.target, 'Android-APK')
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        if: startsWith(matrix.target, 'Android-APK')
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: install dependencies
        if: startsWith(matrix.target, 'Android-APK')
        run: npm ci

      - name: Create Build Folder
        if: startsWith(matrix.target, 'Android-APK')
        run: npm run build

      - name: Add android folder if not present
        if: startsWith(matrix.target, 'Android-APK')
        run: if [ ! -d "./android" ]; then npx cap add android; fi

      - name: Capacitor update
        if: startsWith(matrix.target, 'Android-APK')
        run: npx cap update

      - name: Capacitor sync
        if: startsWith(matrix.target, 'Android-APK')
        run: npx cap sync

      - name: Generate icons and splash screen to android folder
        if: startsWith(matrix.target, 'Android-APK')
        run: if [ -d "./resources" ]; then npm install @capacitor/assets --save-dev && npx capacitor-assets generate --android; fi

      - name: Set Version
        if: startsWith(matrix.target, 'Android-APK')
        run: npx capacitor-set-version . -v ${{ needs.prepare.outputs.version }} -b ${{ github.run_number }} --json

      - name: Build app bundle
        if: startsWith(matrix.target, 'Android-APK')
        run: cd android && ./gradlew bundle && ./gradlew assembleDebug

      - name: Extract Android signing key from env
        if: startsWith(matrix.target, 'Android-APK')
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE }}" > android/release.jks.base64
          base64 -d android/release.jks.base64 > android/release.decrypted.jks

      - name: Sign dev build
        if: startsWith(matrix.target, 'Android-APK')
        run: jarsigner -keystore android/release.decrypted.jks -storepass "${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" -signedjar ./android/app/build/outputs/bundle/release/app-release-signed.aab ./android/app/build/outputs/bundle/release/app-release.aab blade

      - name: Check folder content of android output
        if: startsWith(matrix.target, 'Android-APK')
        run: ls ./android/app/build/outputs/bundle/release

      - name: Upload release bundle
        if: startsWith(matrix.target, 'Android-APK') && ((startsWith(github.event.head_commit.message, 'Release') != true) || github.event.inputs.release == 'No')
        uses: actions/upload-artifact@v3
        with:
          name: yeonic-${{ needs.prepare.outputs.version }}
          path: ./android/app/build/outputs/bundle/release/app-release-signed.aab
          retention-days: 60

      - name: Upload debug bundle
        if: startsWith(matrix.target, 'Android-APK') && ((startsWith(github.event.head_commit.message, 'Release') != true) || github.event.inputs.release == 'No')
        uses: actions/upload-artifact@v3
        with:
          name: yeonic-${{ needs.prepare.outputs.version }}-debug
          path: ./android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 60

      - name: Upload Android-APK to Release
        if: startsWith(matrix.target, 'Android-APK') && ((startsWith(github.event.head_commit.message, 'Release') == true) || github.event.inputs.release == 'Yes')
        uses: YeonV/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: ./android/app/build/outputs/apk/debug/app-debug.apk
          asset_name: yeonic-${{ needs.prepare.outputs.version }}-android.apk
          asset_content_type: application/vnd.android.package-archive

  Build_Desktop:
    needs: prepare
    permissions: write-all
    continue-on-error: true
    if: startsWith(github.event.head_commit.message, 'Release') || startsWith(github.event.head_commit.message, 'Build')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]
        include:
          - os: ubuntu-latest
            title: Linux
            postfix: -linux.snap
            mime: application/x-snap
            postfix2: -linux.AppImage
            mime2: application/x-executable
          - os: windows-latest
            title: Windows
            postfix: -win-setup.exe
            mime: application/x-msdownload
            postfix2: -win.zip
            mime2: application/zip
          - os: macos-latest
            title: macOS
            postfix: .dmg
            mime: application/octet-stream
            postfix2: -mac.zip
            mime2: application/zip
          - os: macos-14
            title: macOS-M1
            postfix: -arm64.dmg
            mime: application/octet-stream
            postfix2: -arm64-mac.zip
            mime2: application/zip
    runs-on: ${{ matrix.os }}
    name: Build Desktop (${{ matrix.title }})
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: install dependencies
        run: npm ci

      - name: Build Web App
        run: npm run build

      - name: Build Electron app
        run: |
          npx --yes cap sync @capacitor-community/electron
          npm run build-electron
          cd electron
          npm ci
          npm version ${{ needs.prepare.outputs.version }}
          npm run build && npx --yes electron-builder build -c ./electron-builder.config.json --publish never
          cd ..

      - name: Upload Binary to Release
        if: startsWith(github.event.head_commit.message, 'Release') || github.event.inputs.release == 'Yes'
        uses: YeonV/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: ./electron/dist/yeonic-${{ needs.prepare.outputs.version }}${{ matrix.postfix }}
          asset_name: yeonic-${{ needs.prepare.outputs.version }}${{ matrix.postfix }}
          asset_content_type: application/octet-stream

      - name: Upload Binary to Workflow
        if: startsWith(github.event.head_commit.message, 'Build') || github.event.inputs.release == 'No'
        uses: actions/upload-artifact@v3
        with:
          name: yeonic-${{ needs.prepare.outputs.version }}${{ matrix.postfix }}
          path: ./electron/dist/yeonic-${{ needs.prepare.outputs.version }}${{ matrix.postfix }}
          retention-days: 60

      - name: Upload Binary 2 to Release
        if: startsWith(github.event.head_commit.message, 'Release') || github.event.inputs.release == 'Yes'
        uses: YeonV/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.prepare.outputs.upload_url }}
          asset_path: ./electron/dist/yeonic-${{ needs.prepare.outputs.version }}${{ matrix.postfix2 }}
          asset_name: yeonic-${{ needs.prepare.outputs.version }}${{ matrix.postfix2 }}
          asset_content_type: application/octet-stream

      - name: Upload Binary 2 to Workflow
        if: startsWith(github.event.head_commit.message, 'Build') || github.event.inputs.release == 'No'
        uses: actions/upload-artifact@v3
        with:
          name: yeonic-${{ needs.prepare.outputs.version }}${{ matrix.postfix2 }}
          path: ./electron/dist/yeonic-${{ needs.prepare.outputs.version }}${{ matrix.postfix2 }}
          retention-days: 60

      - name: Send Discord Release Post
        if: startsWith(matrix.os, 'ubuntu') && (github.event.inputs.release == 'Yes' || startsWith(github.event.head_commit.message, 'Release'))
        run: |
          curl -H "Content-Type: application/json" -d '{"content": "**[DOWNLOAD]** <https://github.com/YeonV/yeonic/releases/tag/${{ env.action_state }}>\n\n**[PREVIEW]** <https://yeonv.github.io/yeonic/>"}' ${{ secrets.DISCORD_RELEASE_WEBHOOK }}

      - name: Send Discord Beta Post
        if: startsWith(matrix.os, 'ubuntu') && (github.event.inputs.release == 'No' || startsWith(github.event.head_commit.message, 'Build'))
        run: |
          RUN_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -H "Content-Type: application/json" -d '{"content": "**[DOWNLOAD]** <'$RUN_URL'>\n\n**[PREVIEW]** <https://yeonv.github.io/yeonic/>"}' ${{ secrets.DISCORD_BETA_WEBHOOK }}
